### ISSUE TITLE
Listing the products

### ISSUE THREAD

**Issue by mansivirani** [NYU-DevOps-Charlie-CSCI-GA-3033-013/products#15]
Listing all the products left in the inventory. Products with "products_remaining" = 0 will not be displayed.

Eg: localhost:5000/products/list

**Comment by NicholasHyland** [comment]
I just realised that the test case for listing the product does not seem sufficient. The code for the function does seem correct as it is relatively easy to implement, but it might be good to fix up the test case. 

The only assertion is: 
self.assertTrue( len(resp.data) > 0 ), which does not test the method completely.

**Comment by ephraimrosenfeld** [comment]
I think it's common for these kinds of GET requests to have a size-limit attribute, where you specify the number of results to return; and if no size-limit is provided, then the API returns a subset of a predetermined, default size.

While our current sample schema is relatively small e.g. a few dozen entries, a fully-developed API that uses a large data-store could have thousands or millions of entries. In such cases it makes sense to have a default limit on the result-set.

See the example [here](http://developer.infoconnect.com/guide/paging-results).

I would therefore suggest that as part of this issue we should add a _limit_ attribute URL attribute that is used by the `list_products()` method during the `GET /products` request to limit the result set; and a default of 10 or 20 elements should be returned if no such limit is specified.

**Comment by ephraimrosenfeld** [comment]
Following up with the question of providing test-cases to provide better coverage, we could have the following: assume we have three products in our test class as we currently do; then we would write the following two test cases:

1. `GET /products` -> no limit is specified, all products are returned, so check that the size of the result is the same as the sample repository data-structure (i.e. three)
2. `GET /products?limit=2` -> check that the size of the result-set is only two

Really we could add more data to the test class so that we ensure that Test Case 1) returns the default size-limit.
